[package]
name = "data_gen"
version = "0.1.0"
edition = "2021"

[dependencies]
tiny-skia = "*"
cosmic-text = "*"
fontdb = "*"
rand = "*"
mathjax = { version = "*", default-features = false, features = ["node", "image"] }
zip = "*"
indicatif = "*"
image = "*"