name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        cd data_gen
        cargo build --release

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-output
        path: data_gen/target/release/data_gen
